Repository containeroo/SyncFlaer, pull requests merged in 2023-01, with the labels that each got.

#159 Update deps, fix trailing dot in additionalRecords
  .github/workflows/push.yml
  CHANGELOG.md
  LICENSE
  README.md
  cmd/syncflaer/main.go
  go.mod
  go.sum
  internal/additionalRecords.go
Labels: enhancement, dependencies

#161 Minor improvements
  CHANGELOG.md
  cmd/syncflaer/main.go
  internal/additionalRecords.go
Labels: bug

#162 Fix typo in example config
  configs/config.yml
Labels: documentation
